version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/lbsfbs
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t shannonzhang/lbsfbs .
          docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
          docker push shannonzhang/lbsfbs

